import { BrowserWindow, app, dialog } from 'electron'
import { autoUpdater } from 'electron-updater'
import log from 'electron-log/main'
import { is } from '@electron-toolkit/utils'
import type { UpdateEventPayload } from '../shared/session'

/** Must match electron-builder.yml → publish */
const GITHUB_FEED = {
  provider: 'github' as const,
  owner: 'vallades',
  repo: 'simplepad',
  private: false,
  releaseType: 'release' as const
}

const UPDATE_CHANNEL = 'latest'

let initialized = false
let checking = false
/** Last check was silent (background) — suppress noisy toasts for checking/not-available */
let lastCheckSilent = false

function broadcast(payload: UpdateEventPayload): void {
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) {
      win.webContents.send('update:event', payload)
    }
  }
}

function logUpdaterState(label: string): void {
  log.info(`[updater] ${label}`, {
    appVersion: app.getVersion(),
    isPackaged: app.isPackaged,
    isDev: is.dev,
    channel: autoUpdater.channel,
    autoDownload: autoUpdater.autoDownload,
    allowPrerelease: autoUpdater.allowPrerelease,
    currentVersion: autoUpdater.currentVersion?.version,
    platform: process.platform,
    arch: process.arch
  })
}

/**
 * Configures electron-updater against GitHub Releases.
 *
 * Production feed comes from `app-update.yml` (generated by electron-builder from
 * `publish:`). We also call `setFeedURL` + `channel: latest` so the feed is
 * explicit even if resources are missing / stale.
 *
 * Flow for end users (packaged app):
 * 1. Bump version + tag vX.Y.Z → Release workflow uploads installers + latest*.yml
 * 2. On launch, app checks GitHub for version > app.getVersion()
 * 3. If found: toast "disponível — baixando", auto download
 * 4. When done: toast + dialog "Reiniciar agora?" → quitAndInstall
 *
 * Dev (`npm run dev`): no auto-check; manual "Ajuda → Verificar atualizações"
 * uses forceDevUpdateConfig + dev-app-update.yml (or the same GitHub feed).
 */
export function setupAutoUpdater(): void {
  if (initialized) return
  initialized = true

  // Full file log under userData/logs (main.log)
  autoUpdater.logger = log
  // electron-log transport already initialized in main/index.ts
  log.transports.file.level = 'info'
  log.transports.console.level = is.dev ? 'debug' : 'info'

  autoUpdater.autoDownload = true
  autoUpdater.autoInstallOnAppQuit = true
  autoUpdater.allowPrerelease = false
  autoUpdater.allowDowngrade = false
  // Explicit channel → latest.yml / latest-mac.yml / latest-linux.yml
  autoUpdater.channel = UPDATE_CHANNEL

  try {
    // Explicit GitHub feed (mirrors electron-builder publish + app-update.yml).
    // Channel is set on autoUpdater.channel (latest → latest.yml / latest-mac.yml).
    autoUpdater.setFeedURL(GITHUB_FEED)
    log.info('[updater] setFeedURL', GITHUB_FEED, `channel=${UPDATE_CHANNEL}`)
  } catch (error) {
    // Fall back to app-update.yml embedded by electron-builder
    log.warn('[updater] setFeedURL failed — using app-update.yml if present', error)
  }

  if (is.dev) {
    // Loads dev-app-update.yml from project root (generic or github provider)
    autoUpdater.forceDevUpdateConfig = true
    log.info('[updater] dev mode — forceDevUpdateConfig=true (manual check only)')
  }

  logUpdaterState('configured')

  autoUpdater.on('checking-for-update', () => {
    checking = true
    log.info('[updater] event:checking-for-update', {
      current: app.getVersion(),
      silent: lastCheckSilent
    })
    broadcast({ type: 'checking', silent: lastCheckSilent })
  })

  autoUpdater.on('update-available', (info) => {
    checking = false
    log.info('[updater] event:update-available', {
      from: app.getVersion(),
      to: info.version,
      files: info.files?.map((f) => f.url),
      path: info.path,
      releaseDate: info.releaseDate
    })
    // Always notify when something will download
    broadcast({ type: 'available', version: info.version, silent: false })
  })

  autoUpdater.on('update-not-available', (info) => {
    checking = false
    log.info('[updater] event:update-not-available', {
      installed: app.getVersion(),
      feedVersion: info.version,
      reason: 'feed version <= installed (or same channel has nothing newer)'
    })
    broadcast({ type: 'not-available', version: info.version, silent: lastCheckSilent })
  })

  autoUpdater.on('download-progress', (progress) => {
    const percent = Math.round(progress.percent)
    log.info(
      `[updater] event:download-progress ${percent}%`,
      `${Math.round(progress.bytesPerSecond / 1024)} KiB/s`,
      `${Math.round(progress.transferred / 1024 / 1024)}/${Math.round(progress.total / 1024 / 1024)} MiB`
    )
    broadcast({
      type: 'progress',
      percent,
      message: `${percent}%`,
      silent: false
    })
  })

  autoUpdater.on('update-downloaded', (info) => {
    checking = false
    log.info('[updater] event:update-downloaded', info.version)
    broadcast({ type: 'downloaded', version: info.version, silent: false })
    void promptInstall(info.version)
  })

  autoUpdater.on('error', (error) => {
    checking = false
    log.error('[updater] event:error', error)
    broadcast({
      type: 'error',
      message: error instanceof Error ? error.message : String(error),
      silent: lastCheckSilent
    })
  })

  // Packaged production builds only: silent check shortly after launch + daily
  if (!is.dev && app.isPackaged) {
    setTimeout(() => {
      void checkForUpdates({ silent: true })
    }, 8_000)

    setInterval(
      () => {
        void checkForUpdates({ silent: true })
      },
      24 * 60 * 60 * 1000
    )
  } else {
    log.info(
      '[updater] auto-check skipped',
      `(is.dev=${is.dev}, isPackaged=${app.isPackaged}) — use Ajuda → Verificar atualizações`
    )
  }
}

async function promptInstall(version?: string): Promise<void> {
  const window = BrowserWindow.getFocusedWindow() ?? BrowserWindow.getAllWindows()[0] ?? null
  const opts: Electron.MessageBoxOptions = {
    type: 'info',
    title: 'Atualização pronta',
    message: version
      ? `A versão ${version} do SimplePad foi baixada.`
      : 'Uma atualização do SimplePad foi baixada.',
    detail:
      'Reinicie agora para instalar. Você também pode continuar e a atualização será aplicada ao sair do app.',
    buttons: ['Reiniciar agora', 'Depois'],
    defaultId: 0,
    cancelId: 1,
    noLink: true
  }

  try {
    const result = window
      ? await dialog.showMessageBox(window, opts)
      : await dialog.showMessageBox(opts)
    if (result.response === 0) {
      quitAndInstallUpdate()
    }
  } catch (error) {
    log.error('[updater] promptInstall failed', error)
  }
}

export interface CheckUpdatesOptions {
  /** When true, suppress "checking" / "up to date" / error noise in the UI */
  silent?: boolean
}

/**
 * Manual or automatic check. Safe to call multiple times.
 * Prefer this over checkForUpdatesAndNotify so toasts stay under our control.
 */
export async function checkForUpdates(options: CheckUpdatesOptions = {}): Promise<void> {
  if (checking) {
    log.info('[updater] check already in progress — ignored')
    return
  }

  lastCheckSilent = Boolean(options.silent)
  logUpdaterState(`checkForUpdates(silent=${lastCheckSilent})`)

  if (!app.isPackaged && !is.dev) {
    // Unpackaged non-dev is rare; still try
    log.warn('[updater] app is not packaged — update check may fail without feed config')
  }

  try {
    // checkForUpdates (not AndNotify): we own UI via broadcast → toasts
    const result = await autoUpdater.checkForUpdates()
    log.info('[updater] checkForUpdates result', {
      updateInfo: result?.updateInfo
        ? {
            version: result.updateInfo.version,
            files: result.updateInfo.files?.map((f) => f.url),
            path: result.updateInfo.path,
            releaseDate: result.updateInfo.releaseDate
          }
        : null,
      cancellationToken: Boolean(result?.cancellationToken),
      downloadPromise: Boolean(result?.downloadPromise)
    })

    if (!result && !options.silent) {
      broadcast({
        type: 'error',
        message:
          'Não foi possível iniciar a verificação. Confira se a Release no GitHub tem latest.yml / latest-mac.yml / latest-linux.yml e versão maior que a instalada.',
        silent: false
      })
    }
  } catch (error) {
    log.error('[updater] checkForUpdates failed', error)
    if (!options.silent) {
      const msg = error instanceof Error ? error.message : String(error)
      broadcast({
        type: 'error',
        message: msg,
        silent: false
      })
    }
  }
}

/** Quit and install after download (user confirmed or app quit). */
export function quitAndInstallUpdate(): void {
  log.info('[updater] quitAndInstall')
  // isSilent=false, isForceRunAfter=true
  autoUpdater.quitAndInstall(false, true)
}
